### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by toshibochan** [topas/homebridge-rfbuttons#1]
Thanks for share you work!!!!
This plugin is working? How do confg setup?

Thanks

**Comment by topas** [comment]
Hi,

The plugin is already under "heavy" development. :) I hope I will finish it soon. Stay tuned! :) 

The reason why I work on my own version instead of use https://github.com/rainlake/homebridge-platform-rcswitch is I need configuration of more RF433 buttons together with a logic.  

Anyway thank you for your support! :)

**Comment by toshibochan** [comment]
This is for control or rf devices or receiver?
I'm looking homebridge for receiver rf transmission. I have rf wireless door and windows sensors and I want HomeKit give notifications when the sensor is activated.

**Comment by topas** [comment]
This plugin is receiver only. It will be able to handle multiple buttons (rf codes) at once. Now it's using `Switch` service type (after iOS 10.3 release it will use `ProgramableSwitch`). For your case I would fork this plugin and use `ContactSensor` service type (it has great icon in Homekit 😄 )

**Comment by toshibochan** [comment]
Contactsensor need a lot cable to run to the house. 
I try to install this but I don't know how.
https://github.com/mattnewham/homebridge-RFReceiver
Usually I do Sudo npm install -g homebridge-........, but this not working for RFReceiver. I contacted the developer but no response.

**Comment by toshibochan** [comment]
You know how install from github to the homebridge?

**Comment by topas** [comment]
`npm install -g homebridge-plugin-name` works only if the plugin is published to NPM. You can clone git repository to a directory somewhere on you RPI, then run `npm install` there to install local modules and then run `homebridge -D -P /path/to/the/plugin` as described here https://github.com/nfarina/homebridge in Plugin development section. And don't forget to configure it in homebridge's config.json.

**Comment by toshibochan** [comment]
@topas  thanks works!!!! but i have one problem. when homebridge start raspberry pi cpu go to 63% and get super hot. anyone having this problem?

**Comment by topas** [comment]
Sorry, this project is no longer being maintained. I don't have time for it. I'll keep this repo for inspiration.
