### ISSUE TITLE
button presses aren't reliable

### ISSUE THREAD

**Issue by faltim** [topas/homebridge-rfbuttons#2]
First, thx for the plugin!

I have a Problem to connect two RF315. My Data Port is connected to pin 13 (GPIO27). To read out the code of them with 433Utils works fine.
So I installed the plugin and drop this in my config of homebridge:

"platform": "RFButtons",
           "pin": 13,
           "debounceDelay": 300,
           "buttons": [
             {
                "name": "Switch1",
                "codes": [74548]
             },
             {
                "name": "Switch2",
                "codes": [12859572]
             }]
        
In home kit i can see the switches as well, but they don't work. Did someone knows whats the problem? Thx

**Comment by topas** [comment]
Hi, 

Thanks! :) 

Did you set button actions in Homekit app? After a button appears in Homekit app you have to select action (now this plugin supports only Single press).  

Also plugin writes logs about pressing, do you have any records about it?

**Comment by faltim** [comment]
Hi, 
Yes i defined button actions. If I start homebridge with `DEBUG=* homebridge -D` all plugins give me logs without this one. Maybe there is a problem with my installation or with root access or something like this?

After program start, homebridge shows following initiallizing logs:
`[2017-4-29 22:42:06] Initializing RFButtons platform...
[2017-4-29 22:42:06] Initializing platform accessory 'Switch1'...
[2017-4-29 22:42:06] Initializing platform accessory 'Switch2'...`

**Comment by faltim** [comment]
I forgot to add my user account to the gpio group. And I set the pin back to 2. Now I see logs like this:

```
[2017-4-29 23:33:20] Code received: 12859572 pulse length : 402
[2017-4-29 23:33:20] Switch2 pressed
```

But the action i defined in home kit does not work. :(

**Comment by topas** [comment]
So... at least you are receiving signals from the buttons. The next thing you need is a device to control home automatition like iPad or Apple TV, because button press actions are handled like any other Homekit automation. 

But I'm experincing some troubles with Apple TV handling this - maybe there is a bug on Apple side. Automation is working only if Homekit app on iPhone is open and after a day or so Apple TV forget the automation. 

I need to spare some time to rewrite plugin for using different type of switches and try it.

**Comment by faltim** [comment]
I use a Apple TV 4 to control homekit. For a while I've tested some Amazon Dash Buttons. That works fine. But for me the time delay between pressing the button and the automation is to long. So I prefer the solution of this plugin here. 

I defined the action on my IPhone in the details of my Buttons/Switches. There are two options for now. Add a automation for a single or double tap on the button. I tried both and nothing happened :/ 
In the next days I will reinstall homebridge in case of another problem. Maybe thats a way to solve the problem. :)

**Comment by topas** [comment]
You have same setup as me. :)  

When you press a button have you seen little hightlight of the button in Homekit App on iPhone? 

This plugin currently supports only single tap action because of limits of RF433 sniffer (it sends only button press events, not release).

**Comment by topas** [comment]
And other thing... you need Homebridge version at least 0.4.18, but if you have dash buttons working you probably have this version.

**Comment by faltim** [comment]
After reinstall homebridge if i press the buttons they are highlighted in the App but the defined action don't work.

**Comment by topas** [comment]
Thanks for the update. It needs couple minutes to upload automation to Apple TV... but I have issues with button presses reliability anyway. I need more time to test something...

**Comment by faltim** [comment]
Allright. I tested a lot, sometimes it works. I think I have the same problem you described.  
Thank you for your help and your work. 👍 If you need some test persons for the next step, I will do my best.

**Comment by topas** [comment]
Sorry, this project is no longer being maintained. I don't have time for it. I'll keep this repo for inspiration.
