### ISSUE TITLE
cpu used hight and cpu temperature hight

### ISSUE THREAD

**Issue by toshibochan** [topas/homebridge-rfbuttons#3]
when this homebridge is on my pi is super hot and cpu used go to 30%. and even when quit homebridge this plugin don't stop reading the sensor and cpu continuo 30%, and when start homebridge again cpu go up more 30% an become 60% and more every time restart homebridge go up 30%. problem is when quit homebridge look like not quitting using the sensor and every time restart homebridge open new reading on top and cpu get super hot and no memory. anyone having this problem?

**Comment by topas** [comment]
Hi, 
This plugin is in the first alpha version and thanks for your testing.  Currently is using https://www.npmjs.com/package/rpi-433 for reading RF signals, RPI-433 package is using very inefficitent infinite loop for reading RF receiver state. I need time for investigate how to replace the rpi-433 library. But this is one of my many hobby project and my priority is really low. If you can, you can investigate how to replace it and submit a merge request. 
Thanks

**Comment by toshibochan** [comment]
Thanks for the plugin. If use only 30% of the CPU is okay. The problem is when stop the homebridge the PI continue reading in the background and when start the homebridge start new reading on top and use double CPU

**Comment by toshibochan** [comment]
Have to make homebridge to quit rpi-433 when stop homebridge

**Comment by toshibochan** [comment]
Any fix?

**Comment by topas** [comment]
Sorry, this project is no longer being maintained. I don't have time for it. I'll keep this repo for inspiration.
