### ISSUE TITLE
I have a request

### ISSUE THREAD

**Issue by toshibochan** [topas/homebridge-rfbuttons#6]
thanks for make this homebridge.
I was watching youtube videos about how to control rf outlets and I find one using RPI-RF  and this not using the cpu at all. I wondering if can make homebridge-rfbuttons to use RPI-RF.

https://github.com/milaq/rpi-rf
https://www.youtube.com/watch?v=5UUazFbK-Hg&t=270s

thanks

**Comment by topas** [comment]
Sorry, this project is no longer being maintained. I don't have time for it. I'll keep this repo for inspiration.
